name: App

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: ${{ !startsWith(github.event.head_commit.message || '', '[skip ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Print runner context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Repository: ${{ github.repository }}"

      - name: Write keystore
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          echo "Writing keystore..."
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > key.jks

          touch signing.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
          echo "KEYSTORE_ALIAS=${{ secrets.KEY_ALIAS }}" >> signing.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> signing.properties
          echo "KEYSTORE_FILE=../key.jks" >> signing.properties

          # 双写一份,确保兼容 KEY_PASSWORD 与 KEYSTORE_ALIAS_PASSWORD 两种变量名
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> signing.properties
          echo "KEYSTORE_ALIAS_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> signing.properties

          echo "signing.properties content:"
          cat signing.properties

      - name: Write temporary key
        if: hashFiles('key.jks') == ''
        run: |
          echo "Generating temporary debug key..."
          keytool -genkeypair -v \
            -keystore key.jks \
            -storetype JKS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias tempkey \
            -storepass temp1234 \
            -keypass temp1234 \
            -dname "CN=Temp, OU=Temp, O=Temp, L=Temp, ST=Temp, C=CN"

          echo "KEYSTORE_PASSWORD=temp1234" >> signing.properties
          echo "KEYSTORE_ALIAS=tempkey" >> signing.properties
          echo "KEY_ALIAS=tempkey" >> signing.properties
          echo "KEY_PASSWORD=temp1234" >> signing.properties
          echo "KEYSTORE_ALIAS_PASSWORD=temp1234" >> signing.properties
          echo "KEYSTORE_FILE=../key.jks" >> signing.properties

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-app-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-app-${{ github.sha }}
          restore-keys: |
            gradle-builds

      - name: Setup Gradle properties
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=false' >> gradle.properties
          echo 'org.gradle.vfs.watch=false' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8' >> gradle.properties
          echo 'org.gradle.daemon=false' >> gradle.properties
          echo 'android.enableR8.fullMode=false' >> gradle.properties
          echo 'android.enableJetifier=false' >> gradle.properties
          echo 'android.useAndroidX=true' >> gradle.properties
          echo "Gradle properties:"
          cat gradle.properties
      
      - name: Patch build.gradle for CI
        run: |
          echo "Patching manager/build.gradle to disable resource optimization..."
          cp manager/build.gradle manager/build.gradle.backup
          
          # 禁用资源压缩和优化
          sed -i 's/shrinkResources true/shrinkResources false/g' manager/build.gradle
          sed -i 's/minifyEnabled true/minifyEnabled false/g' manager/build.gradle
          
          # 注释掉第89-99行的 collapseReleaseResourceNames 任务
          sed -i '89,99 s/^/\/\/ /' manager/build.gradle
          
          # 注释掉第102行的 finalizedBy 调用
          sed -i "102 s/tasks.getByName('optimizeReleaseResources').finalizedBy(collapseReleaseResourceNames)/\/\/ &/" manager/build.gradle
          
          echo "Modified build.gradle (lines 85-105):"
          sed -n '85,105p' manager/build.gradle

      - name: Clean build
        run: |
          chmod +x gradlew
          ./gradlew clean --no-daemon

      - name: Build with Gradle
        id: buildWithGradle
        run: |
          # 先构建 debug 版本测试
          echo "Building debug APK..."
          ./gradlew :manager:assembleDebug --no-daemon --stacktrace
          
          # 再构建 release 版本
          echo "Building release APK..."
          ./gradlew :manager:assembleRelease --no-daemon --stacktrace --info

          releaseName=$(ls manager/build/outputs/apk/release/*.apk | awk -F '/' '{print $NF}' | sed 's/.apk$//')
          debugName=$(ls manager/build/outputs/apk/debug/*.apk | awk -F '/' '{print $NF}' | sed 's/.apk$//')
          echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          echo "debugName=$debugName" >> $GITHUB_OUTPUT

      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildWithGradle.outputs.releaseName }}
          path: "manager/build/outputs/apk/release/*.apk"

      - name: Upload debug
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildWithGradle.outputs.debugName }}
          path: "manager/build/outputs/apk/debug/*.apk"

      - name: Upload mappings
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: "manager/build/outputs/mapping/release"
